### ISSUE TITLE
About KITTI data folder

### ISSUE THREAD

**Issue by qaazii** [garrickbrazil/M3D-RPN#1]
Hi Author, i found that four folders are used inside kitti folder like (calib,image_2,label_2,prev_2). i got the calibration matrix, images and labels. i am confused what is prev_2 in this dataset. kindly can you explain it. 

thanks in advance.

**Comment by brazgardian** [comment]
The prev_2 folder is downloadable at the KITTI website and contains the 3 of the previous frames for camera 2. However, in this project it isn't used so it is okay to not download. I don't believe there should be problems when those files are not available but please let me know otherwise

**Comment by qaazii** [comment]
There is no problem with the code if i run without prev_2. However the calib, images, and labels folder should be in this path data/kitti/training/ before running split files.
