### ISSUE TITLE
projection_ray_trace

### ISSUE THREAD

**Issue by sshan-zhao** [garrickbrazil/M3D-RPN#15]
Hi, 
It is a nice work!!! Thanks for releasing the source code.
When I study your code, I find there is a function named projection_ray_trace in the file imdb_util.py, but I do not find the definition, can you check it?
Thanks a lot.

**Comment by brazgardian** [comment]
This function is not used for this specific project. It is an artifact leftover from a different project and is harmless for this reason. Sorry for the confusion!
