### ISSUE TITLE
split files error

### ISSUE THREAD

**Issue by qaazii** [garrickbrazil/M3D-RPN#2]
Hi Author, I am working on your code since last two days. in the split files i got the following error
lps@lps-Z370M-D3H:~/M3D-RPN$ python data/kitti_split1/setup_split.py
Traceback (most recent call last):
  File "data/kitti_split1/setup_split.py", line 23, in <module>
    from lib.util import *
ImportError: No module named lib.util
Can you help what to import here please.
Thank you.

**Comment by brazgardian** [comment]
Perhaps it is related to the python version / installation? Can you give some information about what version you are using or more general information about your system? You can also reference the setup & installation section of the readme for more information on versions we used to implement and test this project.

I do not prefer this solution, but if you are desperate you can try to add the M3D-RPN path to your PYTHONPATH environment variable. e.g., 

export PYTHONPATH=~/M3D-RPN:${PYTHONPATH}

**Comment by qaazii** [comment]
> Perhaps it is related to the python version / installation? Can you give some information about what version you are using or more general information about your system? You can also reference the setup & installation section of the readme for more information on versions we used to implement and test this project.
> 
> I do not prefer this solution, but if you are desperate you can try to add the M3D-RPN path to your PYTHONPATH environment variable. e.g.,
> 
> export PYTHONPATH=~/M3D-RPN:${PYTHONPATH}


Thank you so much for your reply.
you are right. it was python problem. i have python 2.7 and python 3.5 and 3.6 in my linux system. i forgot to write python3. it worked now.
