### ISSUE TITLE
subprocess.CalledProcessError: Command '[...]' returned non-zero exit status 127

### ISSUE THREAD

**Issue by kaixinbear** [garrickbrazil/M3D-RPN#20]
I tried to run this command to test the model:
`python scripts/test_rpn_3d.py `
and it works well until 
![2019-11-28 16-53-55屏幕截图](https://user-images.githubusercontent.com/33575107/69791581-c2c14480-11ff-11ea-8a8c-8b6ed5773806.png)
`subprocess.CalledProcessError: Command '['/home/gkd/PYTHONPROJECTServer/M3D-RPN-
master/data/kitti_split1/devkit/cpp/evaluate_object', 'output/tmp_results']' ret
urned non-zero exit status 127.`

I traceback the code while finding the error coming from "lib/rpn_util.py"
` with open(os.devnull, 'w') as devnull:`
         `        
out = subprocess.check_output([script, results_path.replace('/data', '')], stderr=devnull)`

how can i modify it to get the right result? 
thx

**Comment by kevin0525** [comment]
try to redo these steps
![image](https://user-images.githubusercontent.com/26395975/69848064-e0e87c80-12b3-11ea-9f12-4e3d5d4374de.png)

**Comment by kaixinbear** [comment]
I reconfig my gcc on the server and get the right result.
