### ISSUE TITLE
Function missed

### ISSUE THREAD

**Issue by SPengLiang** [garrickbrazil/M3D-RPN#24]
Hi,
It is a great work! Thank you for releasing the source code.
I find that function named projection_ray_trace and solve_transform  in the file imdb_util.py are not defned. Can you fix it?
Thanks!

**Comment by brazgardian** [comment]
Hi SPengLiang, thank you! These two functions are not designed to be used in this specific project and are merely artifacts leftover by accident :). Although, their absence should cause no issues

**Comment by SPengLiang** [comment]
Got it, Thank you!
