### ISSUE TITLE
Failure to reproduce results in the paper

### ISSUE THREAD

**Issue by z393** [garrickbrazil/M3D-RPN#26]
The results on my computer is : 
test_iter tmp_results 2d car --> easy: 0.9246, mod: 0.8458, hard: 0.6830
test_iter tmp_results gr car --> easy: 0.2729, mod: 0.2161, hard: 0.1795
test_iter tmp_results 3d car --> easy: 0.2052, mod: 0.1654, hard: 0.1445

test_iter tmp_results 2d pedestrian --> easy: 0.6582, mod: 0.5779, hard: 0.4972
test_iter tmp_results gr pedestrian --> easy: 0.0534, mod: 0.0558, hard: 0.0522
test_iter tmp_results 3d pedestrian --> easy: 0.0483, mod: 0.0513, hard: 0.0467

test_iter tmp_results 2d cyclist --> easy: 0.6431, mod: 0.4087, hard: 0.4072
test_iter tmp_results gr cyclist --> easy: 0.0312, mod: 0.0279, hard: 0.0292
test_iter tmp_results 3d cyclist --> easy: 0.0309, mod: 0.0267, hard: 0.0280

There is a big gap between pedestrians and cyclists in the paper, I don't know why.

**Comment by brazgardian** [comment]
Hi z393, we find that the pedestrians and cyclists are both much less stable in comparison to the car class. This is also lightly noted in our paper. Further, as pointed out in this [paper](https://research.mapillary.com/img/publications/MonoDIS.pdf) and the official [KITTI](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) benchmark, the original metric itself (used in this project) can be relatively less stable too. 

Out of curiosity, feel free to post any of the settings, versions, or hardware for this reproduction!

**Comment by z393** [comment]
My environment is py3.7, cuda9.0,cudnn7.1 torch1.1.0

**Comment by cnexah** [comment]
> The results on my computer is :
> test_iter tmp_results 2d car --> easy: 0.9246, mod: 0.8458, hard: 0.6830
> test_iter tmp_results gr car --> easy: 0.2729, mod: 0.2161, hard: 0.1795
> test_iter tmp_results 3d car --> easy: 0.2052, mod: 0.1654, hard: 0.1445
> 
> test_iter tmp_results 2d pedestrian --> easy: 0.6582, mod: 0.5779, hard: 0.4972
> test_iter tmp_results gr pedestrian --> easy: 0.0534, mod: 0.0558, hard: 0.0522
> test_iter tmp_results 3d pedestrian --> easy: 0.0483, mod: 0.0513, hard: 0.0467
> 
> test_iter tmp_results 2d cyclist --> easy: 0.6431, mod: 0.4087, hard: 0.4072
> test_iter tmp_results gr cyclist --> easy: 0.0312, mod: 0.0279, hard: 0.0292
> test_iter tmp_results 3d cyclist --> easy: 0.0309, mod: 0.0267, hard: 0.0280
> 
> There is a big gap between pedestrians and cyclists in the paper, I don't know why.

I got a similar result with you. Have you solved it ?
My environment is  py3.5, cuda9.0,cudnn7.6 torch1.2.0
