### ISSUE TITLE
Academic fraud, code totally wrong

### ISSUE THREAD

**Issue by lucasjinreal** [garrickbrazil/M3D-RPN#28]
Are u sure the result  can be reproduce?

Are u sure this code can be run? Not mentation there were fuction missing in other issue, but this code is mess and totally wrong:

```
src_anchors = self.anchors[rois[:, 4].cpu().numpy(), :]
```

`rois` is float, how do u able to index an array with float????

**Comment by brazgardian** [comment]
Hi jinfagang, I am sure that the code can run. The rois[:, 4] selects the anchor that the roi belongs to and in the case of my machine are treated as _int_. If you have trouble running the code please check the versions of python, pytorch and CUDA which are detailed more in the readme. 

With the correct versions the results of the paper are generally reproducible, as also discussed in other comments. While there is always randomness to deal with, the code itself should produce reasonable results and at least run with the documented versions and hardware.

**Comment by lucasjinreal** [comment]
rois printed out to be float, how can it be treated as int, by cast? 
Actually, there were a lot logic problem regardless software version, for instance, `self.anchors` is numpy, and rois you were make it tensor previously, how does that able index numpy array with torch.tensor in any version of pytorch?

**Comment by brazgardian** [comment]
In the line you pasted please look at the ".numpy()" call which converts it to be a numpy array.

As stated above, if you are encountering errors then please double check whether your versions match ours or adjust the code for an **upgrade** to newer versions of software as needed. There have been other issues on here which have also done this as well. 

This [issue](https://github.com/garrickbrazil/M3D-RPN/issues/4) appears to occur on newer versions of pytorch and CUDA for example.

**Comment by no-Seaweed** [comment]
It's just a version problem of pytorch - all you need to do is switch torch from your version to V0.4.1. Everything solved. I am not sure why is this man so mad. :)
