### ISSUE TITLE
error with weights after trained mode. 

### ISSUE THREAD

**Issue by qaazii** [garrickbrazil/M3D-RPN#3]
Hi Mr. Garrick Brazil, Thanks for your support. i trained the model. it give me test results after training finished. But when i put the same weights in the path of pretrained weights provided in this  script test_rpn_3d.py. i got this error. 
python3 scripts/test_rpn_3d.py 
Traceback (most recent call last):
  File "scripts/test_rpn_3d.py", line 49, in <module>
    load_weights(net, weights_path, remove_module=True)
  File "/home/lps/M3D-RPN/lib/core.py", line 399, in load_weights
    model.load_state_dict(src_weights)
  File "/home/lps/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RPN:
	Missing key(s) in state_dict: "cls_ble", "bbox_x_ble", "bbox_y_ble", "bbox_w_ble", "bbox_h_ble", "bbox_x3d_ble"

Can you please explain how can i test with my trained weights?
Thanks in advance.

**Comment by brazgardian** [comment]
I'm guessing this will happen when the wrong model is being used? Can you describe what you have done so I can try to reproduce? Or attach/paste the configuration

My guess is that the wrong model <--> weights combination is being used together. For example the config for the depth-aware but the weights for the warmup

**Comment by qaazii** [comment]
while training the model weights are saved in the outoput with "optim_50000_pkl" name but there is no config file. so i used the conf.pkl file that is saved in the output folder.

**Comment by brazgardian** [comment]
Does the same error occur when you use the model_50000_pkl file ? If so then it still seems like a mismatch. Let me know if you can provide the files to take a look. Otherwise I cannot guess too much

**Comment by qaazii** [comment]
![image](https://user-images.githubusercontent.com/13545904/63329889-5ebbf400-c365-11e9-9415-b85c30d166d0.png)

these are the weights stored after training. there is no conf.pkl file. the conf file is in the the screenshot below. 

![image](https://user-images.githubusercontent.com/13545904/63330031-a2aef900-c365-11e9-8896-a243cb42d343.png)

**Comment by brazgardian** [comment]
Try it with the "model_50000_pkl" file, not the optimizer weights to see if that is related

If this doesn't work then perhaps you can upload the weights somehow, and I will debug to see the problem

Also, the configuration file is for the entire experiment so it will not be saved every snapshot. So the conf.pkl you are looking at is the correct one

**Comment by qaazii** [comment]
Thank you so much now., it worked with model_50000_pkl and conf.pkl. Testing now.

can i ask a bit more. i want to ask a bit more in the results. there is three detection 2d, gr and 3d. can you tell me what is gr? 

Moreover I want to change DenseNet to VGG16 for increasing the accuracy? do you think it will increase the accuracy. 

Thank you so much for helping.

**Comment by brazgardian** [comment]
Great. 

2D and 3D detection are probably what they sound like, respectively using 2D and 3D bounding boxes. 

The "gr" is shorthand in my code for ground because this is what the KITTI toolkit sometimes refers to it as. It is actually the birds eye view (BEV) detection results which is the detection in 3D but from a top-down view. The details are a bit in the paper and surely better described on the [KITTI website](http://www.cvlibs.net/datasets/kitti/eval_object.php)

I cannot speculate on VGG16 increasing accuracy, but I doubt it since DenseNet is generally higher performance. Better to try resnet16, resnet50, or resnet100 or something more fancy available in the torchvision package. **Note: it will probably take some effort and debugging to use a new backbone.** Hence, you will need to understand the structure a bit to ensure total network stride=16 and to optionally dilate the bottom layers like we do for DN121

**Comment by qaazii** [comment]
Hi Mr. @garrickbrazil  

I have changes the model to Resnet101 but i didn't used  dilate layers. could you please explain what is the purpose of dilate layers only the greater field of view or anything else. 
And please can you tell me the results are based on IOU > 0.7 or 0.5? 
the results i get from resnet101 without dilation layers are the following:

test_iter 40000 2d car --> easy: 0.8780, mod: 0.8227, hard: 0.6661
test_iter 40000 gr car --> easy: 0.1838, mod: 0.1416, hard: 0.1247
test_iter 40000 3d car --> easy: 0.1232, mod: 0.1076, hard: 0.0811
test_iter 40000 2d pedestrian --> easy: 0.6601, mod: 0.5820, hard: 0.4998
test_iter 40000 gr pedestrian --> easy: 0.0568, mod: 0.0531, hard: 0.0474
test_iter 40000 3d pedestrian --> easy: 0.0486, mod: 0.0454, hard: 0.0412
test_iter 40000 2d cyclist --> easy: 0.6914, mod: 0.5017, hard: 0.4970
test_iter 40000 gr cyclist --> easy: 0.0269, mod: 0.0231, hard: 0.0233
test_iter 40000 3d cyclist --> easy: 0.0198, mod: 0.0104, hard: 0.0096

**Comment by leonzgtee** [comment]
hello, i also encounter the problem of  RuntimeError: Error(s) in loading state_dict for RPN:
Missing key(s) in state_dict: "cls_ble", "bbox_x_ble", "bbox_y_ble", "bbox_w_ble", "bbox_h_ble", "bbox_x3d_ble", and i have used conf_path = '/home/zhuguotao/PycharmProjects/models_git/M3D-RPN-master/output/kitti_3d_multi_main/conf.pkl'
weights_path = '/home/zhuguotao/PycharmProjects/models_git/M3D-RPN-master/output/kitti_3d_multi_main/weights/model_100000_pkl' .only when i change the value of remove_module from True to False in load_weights(net, weights_path, remove_module=True), it can work, could you tell me the the reason for this. thanks

**Comment by z393** [comment]
> Hi Mr. @garrickbrazil
> I have changes the model to Resnet101 but i didn't used  dilate layers. could you please explain what is the purpose of dilate layers only the greater field of view or anything else.
> And please can you tell me the results are based on IOU > 0.7 or 0.5?
> the results i get from resnet101 without dilation layers are the following:
> test_iter 40000 2d car --> easy: 0.8780, mod: 0.8227, hard: 0.6661
> test_iter 40000 gr car --> easy: 0.1838, mod: 0.1416, hard: 0.1247
> test_iter 40000 3d car --> easy: 0.1232, mod: 0.1076, hard: 0.0811
> test_iter 40000 2d pedestrian --> easy: 0.6601, mod: 0.5820, hard: 0.4998
> test_iter 40000 gr pedestrian --> easy: 0.0568, mod: 0.0531, hard: 0.0474
> test_iter 40000 3d pedestrian --> easy: 0.0486, mod: 0.0454, hard: 0.0412
> test_iter 40000 2d cyclist --> easy: 0.6914, mod: 0.5017, hard: 0.4970
> test_iter 40000 gr cyclist --> easy: 0.0269, mod: 0.0231, hard: 0.0233
> test_iter 40000 3d cyclist --> easy: 0.0198, mod: 0.0104, hard: 0.0096
Hey,I want to know how to use the resnet101 as the backbone to train the M3D. Can u share you code with me? thanks very much

**Comment by qaazii** [comment]
> > Hi Mr. @garrickbrazil
> > I have changes the model to Resnet101 but i didn't used  dilate layers. could you please explain what is the purpose of dilate layers only the greater field of view or anything else.
> > And please can you tell me the results are based on IOU > 0.7 or 0.5?
> > the results i get from resnet101 without dilation layers are the following:
> > test_iter 40000 2d car --> easy: 0.8780, mod: 0.8227, hard: 0.6661
> > test_iter 40000 gr car --> easy: 0.1838, mod: 0.1416, hard: 0.1247
> > test_iter 40000 3d car --> easy: 0.1232, mod: 0.1076, hard: 0.0811
> > test_iter 40000 2d pedestrian --> easy: 0.6601, mod: 0.5820, hard: 0.4998
> > test_iter 40000 gr pedestrian --> easy: 0.0568, mod: 0.0531, hard: 0.0474
> > test_iter 40000 3d pedestrian --> easy: 0.0486, mod: 0.0454, hard: 0.0412
> > test_iter 40000 2d cyclist --> easy: 0.6914, mod: 0.5017, hard: 0.4970
> > test_iter 40000 gr cyclist --> easy: 0.0269, mod: 0.0231, hard: 0.0233
> > test_iter 40000 3d cyclist --> easy: 0.0198, mod: 0.0104, hard: 0.0096
> > Hey,I want to know how to use the resnet101 as the backbone to train the M3D. Can u share you code with me? thanks very much



https://github.com/garrickbrazil/M3D-RPN/issues/11#issuecomment-545978876
