### ISSUE TITLE
can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by SamGhK** [garrickbrazil/M3D-RPN#4]
m3d_rpn/lib/loss/rpn_3d.py", line 125, in forward
    src_anchors = self.anchors[rois[:, 4].type(torch.cuda.LongTensor), :]
  File "/home/dev-aug/.local/lib/python3.6/site-packages/torch/tensor.py", line 412, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

m3d_rpn/lib/loss/rpn_3d.py", line 202 - 213, in forward
    bbox_y_tar[bind, :] = transforms[:, 1]
  File "/home/dev-aug/.local/lib/python3.6/site-packages/torch/tensor.py", line 414, in __array__
    return self.numpy().astype(dtype, copy=False)
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

m3d_rpn/lib/loss/rpn_3d.py", line 288, in forward
    src_anchors = self.anchors[rois[fg_inds, 4].type(torch.cuda.LongTensor), :]
  File "/home/dev-aug/.local/lib/python3.6/site-packages/torch/tensor.py", line 412, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

please add .cpu() after each tensor before converting them to numpy array.

**Comment by qaazii** [comment]
yes. add.cpu() in the end of bbox_y_tar[bind, :] = transforms[:, 1] 

like 

bbox_y_tar[bind, :] = transforms.cpu[:, 1]

it worked for me.

**Comment by SamGhK** [comment]
I solved this so I close it

**Comment by z393** [comment]
> yes. add.cpu() in the end of bbox_y_tar[bind, :] = transforms[:, 1]
> 
> like
> 
> bbox_y_tar[bind, :] = transforms.cpu[:, 1]
> 
> it worked for me.

Hey, I want to know how to modify  '' src_anchors = self.anchors[rois[:,4].type(torch.cuda.LongTensor), :]''. thanks!

**Comment by brazgardian** [comment]
I cannot reproduce this error on my machine (there is likely some differences in versions). However, I think you can try to remove the "cuda." from that line as a cleaner way to move it to CPU. It could solve your issue. If it does, then it will likely need to be fixed in 2-3 places in that file

**Comment by SamGhK** [comment]
Thank you for your response. I use Pytorch 1.2. Removing the cuda did the job and as you mentioned is a better and cleaner solution. I want to thank you and your team for your great work and making M3D-RPN public.

**Comment by brazgardian** [comment]
Glad it helped, and thank you for the kind words!
