### ISSUE TITLE
M3D-RPN-master/lib/imdb_util.py", line 336, in read_kitti_cal     return p2 UnboundLocalError: local variable 'p2' referenced before assignment

### ISSUE THREAD

**Issue by zcl912** [garrickbrazil/M3D-RPN#6]
when runnning "python scripts/train_rpn_3d.py --config=kitti_3d_multi_warmup",  it met the error "M3D-RPN-master/lib/imdb_util.py", line 336, in read_kitti_cal return p2 UnboundLocalError: local variable 'p2' referenced before assignment"

**Comment by z393** [comment]
> when runnning "python scripts/train_rpn_3d.py --config=kitti_3d_multi_warmup", it met the error "M3D-RPN-master/lib/imdb_util.py", line 336, in read_kitti_cal return p2 UnboundLocalError: local variable 'p2' referenced before assignment"

I have the same problem, How did you solve it?
