### ISSUE TITLE
about the data

### ISSUE THREAD

**Issue by leonzgtee** [garrickbrazil/M3D-RPN#7]
i have noted that a directory 'kitti_raw['pre'] = os.path.join(base_data, 'kitti', 'training', 'prev_2')' was required when prepare the kitti kitti_split1 dataset in M3D-RPN-master/data/kitti_split1/setup_split.py. why this is need in the project? looking forward to your reply

**Comment by z393** [comment]
> i have noted that a directory 'kitti_raw['pre'] = os.path.join(base_data, 'kitti', 'training', 'prev_2')' was required when prepare the kitti kitti_split1 dataset in M3D-RPN-master/data/kitti_split1/setup_split.py. why this is need in the project? looking forward to your reply
Actually,this project don't need the 'pre_2'. As the author said in the closed problem#1. :)

**Comment by leonzgtee** [comment]
thanks you
